# Generated by Django 4.1.1 on 2022-09-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='static/profiles'),
        ),
    ]
